// ДПБ_История — замороженная история по ПБЕ (янв.2024 — июль 2026) с листа «ПБЕ_данные (историч.)»
// через именованный диапазон ДПБ_ИсторияДиапазон = 'ПБЕ_данные (историч.)'!$B$6:$I$20000
// Столбцы по позиции: B Период | C Год | D №мес | E ПБЕ | F ДЗ | G Авансы | H Оборот Дт | I Оборот Кт
let
    Источник = Excel.CurrentWorkbook(){[Name = "ДПБ_ИсторияДиапазон"]}[Content],
    Имена = Table.ColumnNames(Источник),
    Выбрано = Table.SelectColumns(Источник, {Имена{0}, Имена{3}, Имена{4}, Имена{5}, Имена{6}, Имена{7}}),
    Переименовано = Table.RenameColumns(Выбрано, List.Zip({
        {Имена{0}, Имена{3}, Имена{4}, Имена{5}, Имена{6}, Имена{7}},
        {"Период", "ПБЕ", "ДЗТг", "АвансыТг", "ОборотДтТг", "ОборотКтТг"}})),
    НеПустые = Table.SelectRows(Переименовано, each [Период] <> null and [ПБЕ] <> null
        and Text.Trim(Text.From([ПБЕ])) <> ""),
    Типы = Table.TransformColumnTypes(НеПустые, {{"Период", type date}, {"ПБЕ", type text},
        {"ДЗТг", type number}, {"АвансыТг", type number}, {"ОборотДтТг", type number}, {"ОборотКтТг", type number}}),
    Нули = Table.ReplaceValue(Типы, null, 0, Replacer.ReplaceValue, {"ДЗТг", "АвансыТг", "ОборотДтТг", "ОборотКтТг"}),
    ИменаЧистые = Table.TransformColumns(Нули, {{"ПБЕ", Text.Trim, type text}})
in
    ИменаЧистые
