// Имя запроса: ДП_История
// Загрузка: «Только создать подключение» (без листа, без модели данных)
//
// Читает замороженную историю янв.2024 — июль 2026 с листа « Представительства (историч.)»
// через именованный диапазон ДП_ИсторияДиапазон = ' Представительства (историч.)'!$B$6:$I$20000
// Столбцы диапазона по порядку: B Период | C Год | D №мес | E Представительство |
//                               F Выручка | G Себестоимость | H Запасы на складах | I Товар в пути
// Берём столбцы по ПОЗИЦИИ, а не по имени — так запрос не зависит от того,
// подставит Excel заголовки или нет.

let
    Источник = Excel.CurrentWorkbook(){[Name = "ДП_ИсторияДиапазон"]}[Content],
    Имена = Table.ColumnNames(Источник),
    Выбрано = Table.SelectColumns(Источник, {Имена{0}, Имена{3}, Имена{4}, Имена{5}, Имена{6}, Имена{7}}),
    Переименовано = Table.RenameColumns(Выбрано, List.Zip({
        {Имена{0}, Имена{3}, Имена{4}, Имена{5}, Имена{6}, Имена{7}},
        {"Период", "Представительство", "ВыручкаТг", "СебестоимостьТг", "ЗапасыСкладТг", "ТоварВПутиТг"}})),
    НеПустые = Table.SelectRows(Переименовано, each [Период] <> null and [Представительство] <> null
        and Text.Trim(Text.From([Представительство])) <> ""),
    Типы = Table.TransformColumnTypes(НеПустые, {
        {"Период", type date}, {"Представительство", type text},
        {"ВыручкаТг", type number}, {"СебестоимостьТг", type number},
        {"ЗапасыСкладТг", type number}, {"ТоварВПутиТг", type number}}),
    Нули = Table.ReplaceValue(Типы, null, 0, Replacer.ReplaceValue,
        {"ВыручкаТг", "СебестоимостьТг", "ЗапасыСкладТг", "ТоварВПутиТг"}),
    ИменаЧистые = Table.TransformColumns(Нули, {{"Представительство", Text.Trim, type text}})
in
    ИменаЧистые
