// Имя запроса: ДП_Представительства
// Загрузка: «Только создать подключение» + «Добавить эти данные в модель данных»
//
// Справочник представительств, по которому работают срезы.
//   Класс ABC — по выручке за последние 12 закрытых месяцев:
//       A = представительства, дающие первые 80% выручки, B = следующие 15%, C = остальные 5%.
//   Статус — на последний закрытый месяц:
//       «1 · Продаёт»                     — были продажи за последние 3 месяца;
//       «2 · Запасы без продаж 3 мес.»    — продаж 3 месяца нет, а запасы есть (главный риск неликвида);
//       «3 · Неактивно»                   — нет ни продаж, ни запасов.
// Класс и статус пересчитываются сами при каждом «Обновить всё».

let
    Факт = ДП_Факт,
    ПоследнийМесяц = List.Max(Факт[Период]),
    Граница12 = Date.EndOfMonth(Date.AddMonths(ПоследнийМесяц, -12)),
    Граница3 = Date.EndOfMonth(Date.AddMonths(ПоследнийМесяц, -3)),

    Имена = Table.Distinct(Table.SelectColumns(Факт, {"Представительство"})),
    Выр12 = Table.Group(Table.SelectRows(Факт, each [Период] > Граница12), {"Представительство"},
        {{"Выручка_12м", each List.Sum([ВыручкаТг]), type number}}),
    Выр3 = Table.Group(Table.SelectRows(Факт, each [Период] > Граница3), {"Представительство"},
        {{"Выручка_3м", each List.Sum([ВыручкаТг]), type number}}),
    ЗапПосл = Table.Group(Table.SelectRows(Факт, each [Период] = ПоследнийМесяц), {"Представительство"},
        {{"Запасы_посл", each List.Sum([ЗапасыТг]), type number}}),

    Ш1 = Table.ExpandTableColumn(Table.NestedJoin(Имена, {"Представительство"}, Выр12, {"Представительство"}, "т", JoinKind.LeftOuter), "т", {"Выручка_12м"}),
    Ш2 = Table.ExpandTableColumn(Table.NestedJoin(Ш1, {"Представительство"}, Выр3, {"Представительство"}, "т", JoinKind.LeftOuter), "т", {"Выручка_3м"}),
    Ш3 = Table.ExpandTableColumn(Table.NestedJoin(Ш2, {"Представительство"}, ЗапПосл, {"Представительство"}, "т", JoinKind.LeftOuter), "т", {"Запасы_посл"}),
    Нули = Table.ReplaceValue(Ш3, null, 0, Replacer.ReplaceValue, {"Выручка_12м", "Выручка_3м", "Запасы_посл"}),

    Сорт = Table.Buffer(Table.Sort(Нули, {{"Выручка_12м", Order.Descending}, {"Представительство", Order.Ascending}})),
    Положит = List.Transform(Сорт[Выручка_12м], each if _ > 0 then _ else 0),
    Итого = List.Sum(Положит),
    Накоп = List.Accumulate(Положит, {0}, (s, x) => s & {List.Last(s) + x}),
    НакопДо = List.RemoveLastN(Накоп, 1),
    СНакоп = Table.FromColumns(Table.ToColumns(Сорт) & {НакопДо}, Table.ColumnNames(Сорт) & {"НакопДо"}),

    ABC = Table.AddColumn(СНакоп, "Класс ABC", each
        if [Выручка_12м] <= 0 then "Нет продаж 12 мес."
        else if [НакопДо] / Итого < 0.8 then "A · 80% выручки"
        else if [НакопДо] / Итого < 0.95 then "B · следующие 15%"
        else "C · хвост 5%", type text),
    Статус = Table.AddColumn(ABC, "Статус", each
        if [Выручка_3м] > 0 then "1 · Продаёт"
        else if [Запасы_посл] > 0 then "2 · Запасы без продаж 3 мес."
        else "3 · Неактивно", type text),
    Итог = Table.SelectColumns(Статус, {"Представительство", "Класс ABC", "Статус", "Выручка_12м"})
in
    Итог
