// Имя запроса: ДП_Параметры
// Загрузка: «Только создать подключение» + «Добавить эти данные в модель данных»
//
// Читает маленькую «умную» таблицу tblДП_Параметры (лист ДП_Своды, см. инструкцию, шаг 2):
//   Цель_DIO   — целевая оборачиваемость запасов, дней (по умолчанию = Параметры!C23, т.е. 45);
//   Порог_доли — минимальная доля в выручке, начиная с которой представительство
//                попадает в «Топ-10 ухудшения DIO» (0,001 = 0,1%), чтобы не ловить шум от мелочи.
// После изменения значений нажмите «Обновить всё».

let
    Источник = Excel.CurrentWorkbook(){[Name = "tblДП_Параметры"]}[Content],
    Типы = Table.TransformColumnTypes(Источник, {{"Цель_DIO", type number}, {"Порог_доли", type number}})
in
    Типы
