// Имя запроса: ДП_Сверка
// Загрузка: «Таблица» на новый лист ДП_Сверка (в модель данных НЕ добавлять)
//
// Автоматическая проверка после каждого обновления: сумма по всем представительствам
// за каждый месяц сравнивается с итогами компании, которые идут в общую модель
// (запросы «Продажи» и «Запасы» → листы PQ_Продажи / PQ_Запасы → лист «Данные»).
//   Выручка и себестоимость проверяются за все месяцы.
//   Запасы — только за новые месяцы (история на листе представительств уже сверена с «Данные» до копейки).
// Статус «OK» — расхождение не больше 1 ₸. «РАСХОЖДЕНИЕ» — смотрите, в каком столбце Δ.

let
    ПоследняяДатаИстории = List.Max(ДП_История[Период]),
    ФактМес = Table.Group(ДП_Факт, {"Период"}, {
        {"Выручка_дашборд", each List.Sum([ВыручкаТг]), type number},
        {"Себест_дашборд", each List.Sum([СебестоимостьТг]), type number},
        {"Склад_дашборд", each List.Sum([ЗапасыСкладТг]), type number},
        {"Путь_дашборд", each List.Sum([ТоварВПутиТг]), type number}}),
    П = Table.NestedJoin(ФактМес, {"Период"}, Продажи, {"Период"}, "П", JoinKind.LeftOuter),
    П2 = Table.ExpandTableColumn(П, "П", {"Выручка_без_НДС", "Себестоимость"}, {"Выручка_модель", "Себест_модель"}),
    З = Table.NestedJoin(П2, {"Период"}, Запасы, {"Период"}, "З", JoinKind.LeftOuter),
    З2 = Table.ExpandTableColumn(З, "З", {"Запасы_склад", "Товар_в_пути"}, {"Склад_модель", "Путь_модель"}),
    Н = (x) => if x = null then 0 else x,
    Д1 = Table.AddColumn(З2, "Δ_Выручка", each Н([Выручка_дашборд]) - Н([Выручка_модель]), type number),
    Д2 = Table.AddColumn(Д1, "Δ_Себестоимость", each Н([Себест_дашборд]) - Н([Себест_модель]), type number),
    Д3 = Table.AddColumn(Д2, "Δ_Склад", each if [Период] > ПоследняяДатаИстории
        then Н([Склад_дашборд]) - Н([Склад_модель]) else null, type nullable number),
    Д4 = Table.AddColumn(Д3, "Δ_В_пути", each if [Период] > ПоследняяДатаИстории
        then Н([Путь_дашборд]) - Н([Путь_модель]) else null, type nullable number),
    Статус = Table.AddColumn(Д4, "Статус", each
        if Number.Abs([Δ_Выручка]) <= 1 and Number.Abs([Δ_Себестоимость]) <= 1
            and ([Δ_Склад] = null or Number.Abs([Δ_Склад]) <= 1)
            and ([Δ_В_пути] = null or Number.Abs([Δ_В_пути]) <= 1)
        then "OK" else "РАСХОЖДЕНИЕ", type text),
    Типы = Table.TransformColumnTypes(Статус, {{"Период", type date}}),
    Сорт = Table.Sort(Типы, {{"Период", Order.Descending}})
in
    Сорт
