// Тек_Итог — текущая оборачиваемость по представительствам на отчётную дату.
//   DIO на дату = Остаток на дату * Дней (число отчётной даты) / Себестоимость с 1-го числа месяца.
//   Остаток на дату — из OLAP (куб Remainder_V1). Для сравнения — DIO прошлого месяца по остаткам на складах
//   на конец прошлого месяца (та же база: склад, без товара в пути) * дней / себестоимость прошлого месяца.
let
    Дата = Тек_Параметры,
    ДнейМес = Date.Day(Дата),
    ПредМес = Date.EndOfMonth(Date.AddMonths(Date.StartOfMonth(Дата), -1)),
    ДнейПМ = Date.Day(ПредМес),

    Пр = Тек_Продажи,
    Скл = Тек_Остатки,
    Ф = Table.SelectRows(ДП_Факт, each [Период] = ПредМес),

    Доб = (t as table, имена as list) as table =>
        List.Accumulate(имена, t, (s, n) => if Table.HasColumns(s, n) then s else Table.AddColumn(s, n, each 0, type number)),
    Все = {"ВыручкаТг", "СебестоимостьТг", "ОстатокТг", "ОстатокШт", "СебПредТг", "ЗапПредТг"},
    A = Доб(Table.SelectColumns(Пр, {"Представительство", "ВыручкаТг", "СебестоимостьТг"}), Все),
    B = Доб(Table.RenameColumns(Table.SelectColumns(Скл, {"Представительство", "СуммаТг", "КоличествоШт"}),
            {{"СуммаТг", "ОстатокТг"}, {"КоличествоШт", "ОстатокШт"}}), Все),
    D = Доб(Table.RenameColumns(Table.SelectColumns(Ф, {"Представительство", "СебестоимостьТг", "ЗапасыСкладТг"}),
            {{"СебестоимостьТг", "СебПредТг"}, {"ЗапасыСкладТг", "ЗапПредТг"}}), Все),
    Сумма = Table.Group(Table.Combine({A, B, D}), {"Представительство"}, {
        {"ВыручкаТг", each List.Sum([ВыручкаТг]), type number},
        {"СебестоимостьТг", each List.Sum([СебестоимостьТг]), type number},
        {"ОстатокТг", each List.Sum([ОстатокТг]), type number},
        {"ОстатокШт", each List.Sum([ОстатокШт]), type number},
        {"СебПредТг", each List.Sum([СебПредТг]), type number},
        {"ЗапПредТг", each List.Sum([ЗапПредТг]), type number}}),
    Непустые = Table.SelectRows(Сумма, each [ВыручкаТг] <> 0 or [СебестоимостьТг] <> 0 or [ОстатокТг] <> 0),

    Классы = Table.SelectColumns(ДП_Представительства, {"Представительство", "Класс ABC"}),
    СКлассом = Table.ExpandTableColumn(Table.NestedJoin(Непустые, {"Представительство"}, Классы, {"Представительство"}, "К", JoinKind.LeftOuter), "К", {"Класс ABC"}),

    Р = Table.AddColumn(СКлассом, "Итог", each [
        #"Выручка с 1-го числа, млн тг" = [ВыручкаТг] / 1000000,
        #"Себестоимость с 1-го числа, млн тг" = [СебестоимостьТг] / 1000000,
        #"Остаток на дату, млн тг" = [ОстатокТг] / 1000000,
        #"Остаток на дату, шт." = [ОстатокШт],
        #"Дней" = ДнейМес,
        #"DIO на дату" = if [СебестоимостьТг] > 0 then [ОстатокТг] * ДнейМес / [СебестоимостьТг] else null,
        #"Себестоимость пред. месяца, млн тг" = [СебПредТг] / 1000000,
        #"Остаток на конец пред. месяца, млн тг" = [ЗапПредТг] / 1000000,
        #"Дней пред. месяца" = ДнейПМ,
        #"DIO пред. месяца" = if [СебПредТг] > 0 then [ЗапПредТг] * ДнейПМ / [СебПредТг] else null
    ]),
    Раскрыто = Table.ExpandRecordColumn(Р, "Итог", {"Выручка с 1-го числа, млн тг", "Себестоимость с 1-го числа, млн тг",
        "Остаток на дату, млн тг", "Остаток на дату, шт.", "Дней", "DIO на дату", "Себестоимость пред. месяца, млн тг",
        "Остаток на конец пред. месяца, млн тг", "Дней пред. месяца", "DIO пред. месяца"}),
    Изм = Table.AddColumn(Раскрыто, "Изменение DIO", each
        if [DIO на дату] <> null and [DIO пред. месяца] <> null then [DIO на дату] - [DIO пред. месяца] else null),
    Выбор = Table.SelectColumns(Изм, {"Представительство", "Класс ABC", "Выручка с 1-го числа, млн тг", "Себестоимость с 1-го числа, млн тг",
        "Остаток на дату, млн тг", "Остаток на дату, шт.", "Дней", "DIO на дату", "Себестоимость пред. месяца, млн тг",
        "Остаток на конец пред. месяца, млн тг", "Дней пред. месяца", "DIO пред. месяца", "Изменение DIO"}),
    Типы = Table.TransformColumnTypes(Выбор, {{"Представительство", type text}, {"Класс ABC", type text},
        {"Выручка с 1-го числа, млн тг", type number}, {"Себестоимость с 1-го числа, млн тг", type number},
        {"Остаток на дату, млн тг", type number}, {"Остаток на дату, шт.", type number}, {"Дней", Int64.Type}, {"DIO на дату", type number},
        {"Себестоимость пред. месяца, млн тг", type number}, {"Остаток на конец пред. месяца, млн тг", type number},
        {"Дней пред. месяца", Int64.Type}, {"DIO пред. месяца", type number}, {"Изменение DIO", type number}}),
    Сорт = Table.Sort(Типы, {{"Выручка с 1-го числа, млн тг", Order.Descending}})
in
    Сорт
